### ISSUE TITLE
How can I convert a trained Tensorflow model to SavedModels

### ISSUE THREAD

**Issue by ikegami-yukino** [ajbouh/tfi#2]
This library has potential for useful.

I want to use *.ckpt (available at https://github.com/tensorflow/models/tree/master/slim#pre-trained-models) format model.
Can I do it?

**Comment by ajbouh** [comment]
Yes! Which slim model would you like to start with?

On Sep 21, 2017 8:56 AM, "IKEGAMI Yukino" <notifications@github.com> wrote:

This library has potential for useful.

I want to use *.ckpt (available at https://github.com/tensorflow/
models/tree/master/slim#pre-trained-models) format model.
Can I do it?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ajbouh/tfi/issues/2>, or mute the thread

**Comment by ikegami-yukino** [comment]
> Which slim model would you like to start with?

I want to use Inception V1 model.
thanks.

**Comment by ajbouh** [comment]
Hi @ikegami-yukino , I've just pushed some new functionality to TFI that makes this much easier. The README.rst on master now outlines how to do exactly what you're asking for.

I've also extracted this to a gist: https://gist.github.com/ajbouh/2b1d076f4af569edeeab819a39184abf

I haven't pushed this to pip yet. Can you try it out without me doing that? Would love confirm that it works for you before I do.

**Comment by ikegami-yukino** [comment]
It works well not only Inception V1 but Inception V2 ~ V4.
Very thanks!

**Comment by ikegami-yukino** [comment]
Can I close this issue?

**Comment by ajbouh** [comment]
Yes, thanks again for filing it
